### ISSUE TITLE
Java FX Application Thread Exception

### ISSUE THREAD

**Issue by jugdemon** [tumcms/MomenTUM#1] opened 2017-10-22 15:51 UTC
I just started to use MomenTUM for my Master's Thesis at ETHZ. I installed it according to the github instructions and I ran the "basicExample" project once. While everything seems to work in general, there is an error message while the visualisation is running. The visualisation is not smooth at all (i.e. on average 200 time steps are skipped) which might be caused by the following error: 

![momentum_error](https://user-images.githubusercontent.com/4126068/31863687-43e6186c-b751-11e7-9310-59292191cf67.png)

I am not sure whether there is an issue with my installation of e(fx)clipse JavaFX or it has to do with the inner working of MomenTUM.

**Comment by PeterMKielar** [comment] 2017-10-27 06:57
Hi jugdemon
Thank you for posting this issue.
I updated the BasicExample and added a readme pdf in the folder:
MomenTUM\momentum-documentation\UserGuide\startHere\BasicExample
So, please try again. 

The exception is based on an ongoing issue in the visualization that emerges if:
You did load the density data without loading the pedestrian data first.
You load multiple pedestrian datasets or multiple density datasets.

The current workflow for using both density and pedestrian data is quite strict:
Load the layout, load pedestrian csv, load density csv.

However, you can skip the density data.

I will leave this issue open until we corrected the visualization load data bugs.
Currently, a student is working on this topic.

Regards
Peter

**Comment by jugdemon** [comment] 2017-10-31 14:03
@PeterMKielar Thank you for the explanation on how to avoid the bug!

**Comment by PeterMKielar** [comment] 2017-12-08 08:19
Duplicate of #9

**Closed by PeterMKielar** 2017-12-08 08:19 UTC
Labels: bug
